#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

echo "validating git message..."

pattern='^(feat|fix|docs|style|refactor|test|chore)(\([a-zA-Z0-9_-]+\))?: .+'

if [[ ! $commit_msg =~ $pattern ]]; then
	echo "invalid commit message"
	echo ""
	echo "use format"
	echo "  type(scope): message"
	echo ""
	echo "examples: "
	echo "  feat(auth): add login feature"
	echo "  fix(api): handled null response"
	echo "  docs(readme): add installation steps"
	echo "  style(code): format with black"
	echo "  refactor(auth): simplify token validation logic"
	echo "  test(api): cover edge cases for response"
	echo "  chore(config): update environment variables"
	exit 1
fi
