#!/bin/bash

echo "running pre commit checks"

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

if [ -z "$files" ]; then
	echo "no python files present"
	exit 0
fi

for file in $files; do
	python3 -m py_compile "$file"
	if [ $? -ne 0 ]; then
		echo "syntax error in $file"
		exit 1
	fi

	if grep -E '^\s*print\(' "$file"; then
		echo "Remove debug  print statements in $file"
		exit 1
	fi
done

echo "All check cleared"
exit 0
